Fix TypeError in jsonrpc.py; __init__() got an unexpected keyword argument 'encoding' in call to json.dumps. This argument was removed from the json library in python 3.